name="Have, Don’t have, There is, There isn’t / 있어요, 없어요"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[]
exercises=[
    """
    S -> 'There is {a:noun}'
    """,
    """
    S -> 'There is no {noun}'
    """,
    """
    S -> 'Have {a:noun}'
    """,
    """
    S -> 'Don`t have {noun}'
    """
]
