name="Please give me... / ... 주세요"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-34-41/lesson-41/#411"
]
exercises=[
    """
    S -> 'Please give me {noun}'
    """
]
