name="What do you want to do? / 뭐 -고 싶어요?"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-17/#co5"
]
exercises=[
    """
    S -> 'What do' P 'want to' V
    P -> 'I' | 'they' | 'you' | 'we'
    V -> '{verb}'
    """,
    """
    S -> 'What does' P 'want to' V
    P -> 'he' | 'she' | 'it'
    V -> '{verb}'
    """
]
