name="But, However / 그렇지만, 그런데"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 2"},
    {resource_name="HTSK", level="Unit 4"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-47/",
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-76-83/lesson-77/#771"
]
exercises=[
    """
    S -> V 'but' V | V 'however' V | Vp 'but' Vp | Vp 'however' Vp | A 'but' A | A 'howevers' A
    V -> '{verb}'
    Vp -> '{verb:past}'
    V -> '{adj}'
    """
]
