name="Don’t do it. / -지 마세요"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-34-41/lesson-40/#407"
]
exercises=[
    """
    S -> 'Don`t {verb}'
    """,
    """
    S -> 'Don`t {verb} like that!'
    """
]
