name="Future Tense / -ㄹ/을 거예요, 할 거예요"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-9-16/unit-1-lesson-9/#ifut"
]
exercises=[
    """
    S -> P 'will' V
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it' |
    V -> '{verb}'
    """
]
