name="Have to, Should, Must / -아/어/여야 되다/하다"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-46/#461"
]
exercises=[
    """
    S -> P H V
    H -> 'have to' | 'should' | 'must'
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it' |
    V -> '{verb}'
    """
]
