name="If, In case / 만약, -(으)면"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-43/#431"
]
exercises=[
    """
    S -> 'If' ANV
    ANV -> '{adj}' | '{noun}' | '{verb}'
    """
]
