name="To be good/poor at … / 잘하다/못하다"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-20/"
]
exercises=[
    """
    S -> P GB V
    GB -> 'good at' | 'poor at'
    P -> 'I am' | 'they are' | 'you are' | 'we are' | 'he is' | 'she is' | 'it is' |
    V -> '{verb:ing}'
    """
]
