name="To like / 좋다 vs. 좋아하다"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-1-8/unit-1-lesson-3/#like"
]
exercises=[
    """
    S -> P 'like' N
    P -> 'I' | 'they' | 'you' | 'we'
    N -> '{noun}'
    """,
    """
    S -> P 'likes' N
    P -> 'he' | 'she' | 'it'
    N -> '{noun}'
    """
]
