name="Even if, Even though / -아/어/여도"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 2"},
    {resource_name="King Sejong Institute Practical Korean", level="3. Intermediate"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-48/#481",
]
exercises=[
    """
    S -> 'Even if {verb} {verb}'
    """
]
