name="Linking Verbs With -아/어/여서"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-17/#co3"
]
exercises=[
    """
    S -> '{verb} and (then) {verb}'
    """
]
