name="Maybe I might… / -(으)ㄹ 수도 있어요"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 5"},
]
links=[
    "https://www.howtostudykorean.com/unit-5/lessons-101-108/lesson-107/#1073c",
    "https://123learnkorean.wordpress.com/2009/08/25/%E3%84%B9%EC%9D%84-%EC%88%98%EB%8F%84-%EC%9E%88%EB%8B%A4-might-verb/"
]
exercises=[
    """
    S -> P 'might {verb}' T
    P -> 'I' | 'you' | 'we' | 'they' | 'he' | 'she' | 'it'
    T -> 'today' | 'tomorrow'
    """,
    """
    S -> '{noun} might change'
    """,
]
