name="Verb Ending / -ë„¤ìš”"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 4"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-76-83/lesson-83/#830"
]
exercises=[
    """
    S -> W '!'
    W -> '{adj}' | '{noun}'
    """
]
