name="I think … (+ future tense) / -(으)ㄴ/(으)ㄹ/ㄴ 것 같다, 한 것 같다, 할 것 같다"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-34-41/lesson-35/#351"
]
exercises=[
    """
    S -> 'I think {noun} will be {adj}.'
    """,
    """
    S -> 'I think {noun} was {adj}.'
    """,
    """
    S -> 'I think' P 'will {verb}.'
    P -> 'he' | 'she' | 'it' | 'I' | 'you' | 'they' | 'we'
    """,
    """
    S -> 'I think' P '{verb:past}.'
    P -> 'he' | 'she' | 'it' | 'I' | 'you' | 'they' | 'we'
    """,
]
