name="It can’t be … / -(으)ㄹ 리가 없어요, 할 리가 없어요"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 6"},
]
links=[
    "https://www.howtostudykorean.com/unit-6/lessons-126-133/lesson-133/#1331"
]
exercises=[
    """
    S -> 'There is no way that the {noun} just {verb:past}'
    """,
    """
    S -> 'There is no way that the {noun} is {adj}'
    """,
]
