name="It is okay to…, You don’t have to… / -아/어/여도 돼요, 해도 돼요"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 2"},
    {resource_name="King Sejong Institute Practical Korean", level="3. Intermediate"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-49/"
]
exercises=[
    """
    S -> 'It is ok to {verb}.'
    """,
    """
    S -> 'It is ok if' P '{verb:3s}.' | P 'does not have to {verb}.'
    P -> 'he' | 'she' | 'it'
    """,
    """
    S -> 'It is ok if' P '{verb}.' | P 'don`t have to {verb}.'
    P -> 'I' | 'you' | 'they' | 'we'
    """,
]
