name="Less, Not completely / ëœ"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-19/#comp32"
]
exercises=[
    """
    S -> '{noun:nonperson} is less {adj}.'
    """,
    """
    S -> P 'did not finish {verb:ing}.'
    P -> 'he' | 'she' | 'it' | 'I' | 'you' | 'they' | 'we'
    """,
]
