name="Most, Best (superlative) / 최상급, 최고"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-19/#comp4"
]
exercises=[
    """
    S -> '{noun} is the most {adj}.'
    """,
    """
    S -> P 'the best at {verb:ing}.'
    P -> 'he is' | 'she is' | 'it is' | 'I am' | 'you are' | 'they are' | 'we are'
    """,
]
