name="Much (more), Much (less) / 훨씬"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-34-41/lesson-34/#345"
]
exercises=[
    """
    S -> '{noun} is much' C '{adj}.'
    C -> 'more' | 'less'
    """
]
