name="To gradually/eventually get to do something / -게 되다, 하게 되다"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 4"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-92-100/lesson-94/#941"
]
exercises=[
    """
    S -> P 'gradually got to {verb}'
    P -> 'I' | 'he' | 'she' | 'it' | 'they' | 'we' | 'you'
    """,
    """
    S -> P 'made {noun} {adj}'
    P -> 'I' | 'he' | 'she' | 'it' | 'they' | 'we' | 'you'
    """,
]
